title: My Portfolio
description: >
  Projects, Experience, and More!

theme: null # You can change this to another supported theme
include:
  - moonwalk

navigation:
  - title: "Home"
    url: "/"
  - title: "Projects"
    url: "/projects"
  - title: "About"
    url: "/about"