title: My Portfolio
description: >
  Projects, Experience, and More!

remote-theme: abhinavs/moonwalk # You can change this to another supported theme
plugins:
  - jekyll-remote-theme

navigation:
  - title: "Home"
    url: "/"
  - title: "Projects"
    url: "/projects"
  - title: "About"
    url: "/about"